name: deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Package and publish to PyPi 📦
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # 4.1.7
      - name: Setup Python 3.9
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # 5.2.0
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv setuptools wheel twine
      - name: Build
        run: |
          pipenv run python setup.py sdist bdist_wheel
      - name: Publish distribution 📦 to Test PyPI
        if: github.event.release.prerelease == true
        uses: pypa/gh-action-pypi-publish@8a08d616893759ef8e1aa1f2785787c0b97e20d6 # 1.10.0
        with:
          password: ${{ secrets.TEST_PYPI_PASSWORD }}
          repository_url: https://test.pypi.org/legacy/
      - name: Publish distribution 📦 to PyPI
        if: github.event.release.prerelease != true
        uses: pypa/gh-action-pypi-publish@8a08d616893759ef8e1aa1f2785787c0b97e20d6 # 1.10.0
        with:
          password: ${{ secrets.PYPI_PASSWORD }}
